root = "."
tmp_dir = "tmp"

[build]
  # Aqu√≠ especificamos la ruta a tu main.go
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  bin = "tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", ".git"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_regex = ["_test.go"]

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"